# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0003_auto_20170331_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishitem',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
