# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0007_auto_20170331_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=32),
        ),
    ]
